### ISSUE TITLE
Is it necessary to add Roles through Rail Console

### ISSUE THREAD

**Issue by sunilkalyan08** [RolifyCommunity/rolify#246]
Hi, I want to appreciate for your contribution about Rolify along with Devise and Cancan. Here my question is Can we add Roles through form which points to Rolify roles tables along with Devise Users table. Like 

E-Mail: Eppo@eppo.com
Password : 123456
Password Confirmation : 123456
Role : Admin
Role will stored on roles table and remaining data will store in users table. Please provide a solution

**Comment by JWesorick** [comment]
Is this really the best way to do this? If I have 20 different roles it seems like my controller is going to look ridiculous.

**Comment by wldcordeiro** [comment]
@JWesorick You can write a 'helper' method that's private that looks like.

```rb
def role_adder(role)
  if params[role] == "1"
    @user.grant(role)
  elsif params[role] == "0"
    @user.remove_role(role)
  end
end
```

Then in your controller you can do something like

```rb
roles = [
  :admin,
  :moderator,
  :other_role
]

roles.each { |r| role_adder(r) }
```

**Comment by itsryandrake** [comment]
What would the view look like with the roles.each loop now?

**Comment by wldcordeiro** [comment]
@itsryandrake something like this though I think you would need to modify the array to store the name you want to display.

```erb
 <fieldset>
  <legend>User Roles</legend>
    <% @roles.each do | role | %>
      <%= f.label(role) do %>
        role.name
       <%= hidden_field_tag(role, 0) %>
       <%= check_box_tag(role, 1, @user.has_role?(role)) %>
    <% end %>
  <% end %>
</fieldset>
```

**Comment by crawfoal** [comment]
I used @wldcordeiro's technique, but I modified it a bit so that adding new roles is easier, and so that you don't have to use hidden fields:

In the view, I have
```erb
<% Role.defined_roles.each do |role|%>
  <%= form.label(role) do %>
    <%= check_box_tag 'user[_roles][]', role, resource.has_role?(role) %>
    <%= role %>
  <% end %>
<% end %>
```
I put an underscore before `roles` to ensure that I wasn't going to call the `roles` method on the user, although I think this isn't actually necessary unless you whitelist `roles` in your strong parameters (which we have no reason to do since we're not including the roles in mass assignment). For more about the name of the checkboxes, see 3:20-4:35 in [Railscast #17 HABTM Checkboxes](http://railscasts.com/episodes/17-habtm-checkboxes?autoplay=true) (or maybe just watch the whole thing if you haven't seen it yet).

In the controller, I have
```ruby
params['user']['_roles'] ||= []
params['user']['_roles'].each do |role|
  resource.add_role role unless resource.has_role? role
end
```

To my role model, I've added
```ruby
def self.defined_roles
  self.all.map { |role| role.name  }
end
```

Then when I'm seeding data, I create a temporary user and add the roles for my application to that user in order to ensure that the roles show up in the view if a particular role hasn't been assigned to a user yet (mainly for my testing). So in `seeds.rb`, I have
```ruby
user = User.create()
[:admin, :moderator].each do |role|
  user.add_role role
end
user.destroy
```
If your user model has validations (that will be triggered on a blank user), you probably should add to that call to `create`.

**Comment by crawfoal** [comment]
In my previous comment, I made a little mistake - the seed data doesn't really apply to testing since seed data isn't (typically) loaded in during testing.

I also ended up changing the `defined_roles` method. Since roles probably aren't added very often, I decided to cache a list of them:

```ruby
  after_save 'self.class.cache_defined_roles'
  def self.cache_defined_roles
    cache = self.unscoped.all.map { |role| role.name  }
    self.singleton_class.instance_eval do
      define_method 'defined_roles' do
        cache
      end
    end
  end

  def self.method_missing(name, *args, &block)
    if name == :defined_roles
      cache_defined_roles
      defined_roles
    else
      super
    end
  end
```
But I'm in the process of learning about metaprogramming, so if you're reading this and something looks fishy, or there's a better way to handle the caching, let me know :)

**Comment by reallyordinary** [comment]
None of the above helped me to figure out how to get role add/editing working through the UI. But this did - https://stackoverflow.com/questions/21688200/rails-4-checkboxes-for-has-and-belongs-to-many-association

**Comment by laptopmutia** [comment]
I think this is should be added to wiki
