### ISSUE TITLE
time to get rid of `has_role` ?

### ISSUE THREAD

**Issue by jjb** [RolifyCommunity/rolify#293]
Perhaps it's time to get rid of `has_role` once and for all. I just got burned by this again and assigned the same role to everyone in my system. luckily it was easy to recover from this time. in the meantime i'm adding this to my User model:

```ruby
  def has_role(*args)
    raise "I think you mean to use User#has_role?, not User#has_role"
  end
```

**Comment by wldcordeiro** [comment]
Removing this now, will be in a commit later today along with a 3.5 release. Hopefully fixing the caching issues.

**Comment by wldcordeiro** [comment]
Has been removed with the release of 3.5.x. Closed.

**Comment by jjb** [comment]
@wldcordeiro what happened to 4.0, since it's an api change?

**Comment by wldcordeiro** [comment]
@jjb 4.0 is still planned but there's a lot of other things planned in 4.0 that haven't been completed. This was a dangerous method that was causing a lot of grief so I decided to kill it sooner rather than hold it up with the other 4.0 changes. 

Also Rolify had a shakeup of its management as the original creator didn't have time to maintain the project so there's some transition pains as myself and other new contributors get acquainted with the codebase and determine what to work on. If you're interested in helping out we're always accepting new contributors. :smile:

**Comment by jjb** [comment]
gotcha

i think everyone always benefits from strict adherence to semantic versioning though

what's wrong with making this one 4 and renaming the current 4 branch to 5?
