### ISSUE TITLE
When the id of a resource is not an integer. 

### ISSUE THREAD

**Issue by DanielOchoa** [RolifyCommunity/rolify#403]
I'm working with a model in which the id's are not integers. For example, they follow the format: `8ccca348-8f3e-42b4-b4f8-a3a52e2ch4dz`. This seems to make certain rolify methods fail. For example: `user.has_role? :admin, employer` throws the following error:

`ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "8ccca348-8f3e-42b4-b4f8-a3a52e2cf1cb"
LINE 1: ...ource_type = 'Employer') AND (roles.resource_id = '8ccca348-...`

Is there any simple workaround for this problem? I'm asking before I try and fork this repo.

**Comment by lorefnon** [comment]
Thanks for reporting this. 

I believe the only thing you would need to ensure is that your `resource_id` in your roles table is a string (rather than an integer). Rolify does not have any expectation with respect to the type of id. But because it is a polymorphic association, it also does not have a way to infer the type of `resource_id`. 

So if you just change the rolify generated migration to use `t.string` for resource_type, rest should work fine. Please let us know if you continue to face problems.

**Comment by DanielOchoa** [comment]
Excellent! Thank you for the detailed and prompt response. 👯
