### ISSUE TITLE
Model.with_roles is undefined

### ISSUE THREAD

**Issue by Zhao-Andy** [RolifyCommunity/rolify#481]
Doesn't seem like there's an actual method `.with_roles`, even though the ReadMe has it. Is this a deprecated method?

**Comment by AncyentMariner** [comment]
@Zhao-Andy  I'm having the same issue.

**Comment by Zhao-Andy** [comment]
@AncyentMariner @dkniffin Seems like the actual method is `Model.with_any_role` or `Model.with_all_roles`, depending on your use case. I ended up using `with_any_role` for mine.

There is a singular version `Model.with_role`, which works for checking for one role. For example: `User.with_role(:admin)`

I found a more accurate documentation in the [Usage wiki](https://github.com/RolifyCommunity/rolify/wiki/Usage).

**Comment by dkniffin** [comment]
Nice. To finish up this issue then, we'd just need to update the Readme. Maybe just linking to the usage docs would be sufficient.

**Comment by sergey-alekseev** [comment]
This is actually confusing, let me clarify.

README.md mentions
```ruby
Forum.with_roles([:admin, :user], current_user)
# => [ list of Forum instances that have role "admin" or "user" bound to them and belong to current_user roles ]
```

`Forum` is a resource model and contains `resourcify`. ([3.2 Configure your resource models](https://github.com/RolifyCommunity/rolify/blob/522c0d7d84a70dd3576b569edf19f9f6cb118a61/README.md#32-configure-your-resource-models))  
The `resourcify` call automatically includes the `Resource` module which contains [`with_roles`](https://github.com/RolifyCommunity/rolify/blob/522c0d7d84a70dd3576b569edf19f9f6cb118a61/lib/rolify/resource.rb#L22) as an alias to `with_role`.  

The aforementioned [Usage Wiki](https://github.com/RolifyCommunity/rolify/wiki/Usage) is a good finding because it contains two separate sections – [`Finders`](https://github.com/RolifyCommunity/rolify/blob/522c0d7d84a70dd3576b569edf19f9f6cb118a61/lib/rolify/finders.rb) methods ([1](https://github.com/RolifyCommunity/rolify/wiki/Usage#finders-methods)) and [`Resource`](https://github.com/RolifyCommunity/rolify/blob/522c0d7d84a70dd3576b569edf19f9f6cb118a61/lib/rolify/resource.rb) methods ([2](https://github.com/RolifyCommunity/rolify/wiki/Usage#resource-role-queries)).

**Comment by EppO** [comment]
Indeed, you can call `.with_role` (or `with_roles` which is an alias) on a model that includes `Resource` module. I confess README can be improved to make it clearer

**Comment by mczal** [comment]
> Indeed, you can call `.with_role` (or `with_roles` which is an alias) on a model that includes `Resource` module. I confess README can be improved to make it clearer

@EppO 
Hey its absolutely can't be an aliases, because the generated query is completely wrong from the general conventions.
`.with_role` should be receiving a single role as parameter
`.with_roles` should be receiving a plural role as parameter 
and the generated query have to adjust those different kind of logic.
