### ISSUE TITLE
How can I use the gem when some of my resources use UUID and some integer IDs ?

### ISSUE THREAD

**Issue by dowi** [RolifyCommunity/rolify#493]
Hi and thanks a lot
I saw the FAQ on UUIDs, but it changes the whole mechanism to use UUID. 
How can I cope with some of my tables use UUID and some regular integer ID?

Thanks a log

**Comment by daviscabral** [comment]
What about having a virtual column there on these models where integer ID is still used as key? I would say that - even that they are using integer IDs, does not hurt to add the UUID column and use a rake task to backfill previous records and set a callback to also do it when creating a new record. Soon you will be able to migrate  - if that's possible and wanted from you - but mainly, no workaround will be necessary. 

BTW, are these tables from the same schema/database?

**Comment by dowi** [comment]
Thanks! thats a great idea.

Those tables are in the same schema

**Comment by Genkilabs** [comment]
I think this is still a relevant issue. In my case I have a table where the column `uuid` is the primary key, but (for various reasons) the attribute `id` is also in use as a legacy identifier.
ie.
```
#Legacy table of records from multiple sources
#Note: id is not guaranteed to be unique because this table contains data from various systems
#Uniqueness can be found with either the primary-key UUID, or the pair [:id, :source] 

class HomogenizedData < ApplicationRecord
	set_primary_key :uuid
```
so
```
> HomogenizedData.first.uuid == HomogenizedData.first.id
false
```
Ideally there should be an option in a Rolify config to identify that the attribute I want to use for the `resource_id` on the joining role is the records `uuid` not the `id`.

**Comment by thomas-mcdonald** [comment]
@Genkilabs in this case do you have mixed uuid + integer primary keys or is this a request to have rolify honour the set_primary_key value? If it's the latter, can you open a new issue?

I'm going to close this specific issue as something we're unlikely to fix - supporting mixed types as a join column is not something that Rails does very well and I think architecturally is awkward. As proposed by @daviscabral a couple of years ago (thanks!) there are application level workarounds for this.

**Comment by freibuis** [comment]
I think this is valid. With more and more ppl using UUID's and bigints for their keys, this will only become a bigger problem in the future.
ways I think that you could solve this.. casting id field (dont recommend) or adding more columns in the roles table


maybe like this

```ruby
    create_table :roles do |t|
      t.string :name
      t.references :resource, polymorphic: true
      t.references :resource_uuid, polymorphic: true
      t.references :resource_string, polymorphic: true
      t.string         :key_type, nil: false

      t.timestamps
    end
```
key_type dictates why colum has the key value

then save in the colum based on the `Model.columns_hash['id'].type`

```
key_type.empty?  resource_id
key_type == :uid    resource_uuid_id
key_type == :string  resource_string_id  # terrible string key
```

tricky on the model_roles.

**Comment by Genkilabs** [comment]
@thomas-mcdonald Thanks for getting back on this. I completely understand what you mean by asking to make joins on an unclear type. However, the solution for the use case does not necessarily require those roles to be served out of the same Role model.

For example, this would be an elegant solution for my use case:
```
#external/partner/legacy resources needs Role unchanged, using an integer id. In my case, read-only access.
#however our new spec calls for UUIDs on new tables. 
#So we will make a new Rolify table with stringified resource_id named UUIDRole.

class User < ApplicationRecord
    #Ideally we could tell Rolify to only use that relation with a specific set of models, leaving the default Role for all other cases
    rolify :role_cname => 'UUIDRole', :only => ['UUIDModelOne', 'UUIDModelTwo']

    #NOTE: The default here should be implicitly 'Role' but it could also be explicit...
    #rolify :role_cname => 'Role'
end
```

Thus, `@user.has_role? :manager, @app` would join using the users_roles table, but `@user.has_role? :manager, @some_uuid_id_model` would join using the users_uuid_roles table. 

(I'm assuming inflection of 'UUID' in an initializer for the above example, otherwise you get 'UuidRole.)

-----

I think the `:except => [Enumerable]` and `:only => [Enumerable]` has a precedent in Rails convention and would be an elegant feature to add to the `:role_cname` directive. 

However, this feature would require Rolify to be aware of all cnames registered for a role-owning-class (User) and would require testing the class of a resource before attempting a join if additional cnames were defined/non-empty. I don't know the performance impact of this, or if it is a desirable enough solution to make a feature request on...

What do you think?
