### ISSUE TITLE
[Question] Check performant multiple user roles

### ISSUE THREAD

**Issue by Piioo** [RolifyCommunity/rolify#546]
I have ten roles and now I want to send the information to the frontend about what roles a user has. I send a hash of these roles.

If I check the roles individually with `has_role?`, a query is executed every time.

Is there a way to get all roles at once (`user.roles`) for one user and run the checks on that array and avoid all the queries?

**Comment by stevenbuccini** [comment]
Yes, you can get all roles for a user by executing `user.roles`. However, this might not give you exactly what you want if you have roles that are scoped to a resource as there will be one role for each resource, even if the `role_name` is the same.

For example:
```ruby
> user.add_role(:admin)
> p1 = Post.create
> p2 = Post.create
> user.add_role(:author, p1)
> user.add_role(:author, p2)
> user.roles.count
=> 3
```

If you want to check if a user has a specific role, I would use `has_any_role?`. But, if you're simply trying to get all roles that a user has in O(1) time, I would suggest (Rails 5+ only):
```ruby
# Given same instantiation as above code block
> user.roles.distinct.select(:name)
=> ["admin", "author"]
```
Here's the query outputted in the console:
```
(0.6ms)  SELECT DISTINCT "roles"."name" FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1  [["user_id", "<user_id>"]]
```

If I am correct and that this functionality isn't currently available with the given methods, I think it would be worth adding. What do you think @thomas-mcdonald?

**Comment by thomas-mcdonald** [comment]
I think I have a similar issue with one of the apps I run. I'm curious what the shape of the question you're trying to answer is. Hypothetical code, is it something like:

```
u.has_roles? [:admin, :reader], resource
=> { admin: false, reader: true}
```

```
u.has_roles? :admin, [r1, r2]
=> { r1.id: false, r2.id: true}
```

or a combination of the both? Bear in mind I'm still discovering some of the surface area of the Rolify API...

@stevenbuccini My gut feel is that exposing something like `user.roles.distinct.select(:name)` would have pretty low uptake because it's not resource scoped, I'd be hesitant to add it to the API.
